# Generated by Django 4.2.29 on 2026-03-24 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('preventive', 'Préventive'), ('corrective', 'Corrective'), ('inspection', 'Inspection')], max_length=15)),
                ('description', models.TextField(verbose_name='Description des travaux')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût (DZD)')),
                ('performed_by', models.CharField(blank=True, max_length=200, verbose_name='Réalisé par')),
                ('date', models.DateField(verbose_name='Date de maintenance')),
                ('next_date', models.DateField(blank=True, null=True, verbose_name='Prochaine maintenance')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='buses.bus')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Breakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description de la panne')),
                ('location_desc', models.CharField(blank=True, max_length=300, verbose_name='Lieu de la panne')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('reported', 'Signalée'), ('in_progress', 'En cours de résolution'), ('resolved', 'Résolue')], default='reported', max_length=15)),
                ('alert_sent', models.BooleanField(default=False, verbose_name='Alerte envoyée')),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True, verbose_name="Heure d'alerte")),
                ('alert_message', models.TextField(blank=True, verbose_name="Message d'alerte du chauffeur")),
                ('root_cause', models.TextField(blank=True, verbose_name='Cause principale de la panne')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Actions effectuées')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='buses.bus')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_breakdowns', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_breakdowns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Panne',
                'verbose_name_plural': 'Pannes',
                'ordering': ['-reported_at'],
            },
        ),
    ]
