# Generated by Django 4.2.29 on 2026-04-16 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Jour')),
                ('status', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('leave', 'Congé'), ('sick', 'Maladie')], default='present', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('auto_generated', models.BooleanField(default=False, verbose_name='Créé automatiquement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='absence_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique absence (journalier)',
                'verbose_name_plural': 'Historique absences (journalier)',
                'ordering': ['-date', 'driver__last_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='absencehistory',
            constraint=models.UniqueConstraint(fields=('driver', 'date'), name='uniq_driver_absence_day'),
        ),
    ]
