# Generated by Django 4.2.29 on 2026-03-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='Immatriculation')),
                ('model', models.CharField(max_length=100, verbose_name='Modèle')),
                ('brand', models.CharField(max_length=100, verbose_name='Marque')),
                ('capacity', models.PositiveIntegerField(default=40, verbose_name='Capacité (places)')),
                ('year', models.PositiveIntegerField(verbose_name='Année')),
                ('status', models.CharField(choices=[('moving', 'En mouvement'), ('stopped', "À l'arrêt"), ('maintenance', 'En maintenance'), ('inactive', 'Inactif')], default='inactive', max_length=15, verbose_name='État')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Bus',
                'ordering': ['plate_number'],
            },
        ),
    ]
