# Generated by Django 4.2.29 on 2026-03-27 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='driver',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bus',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bus',
            name='capacity',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='bus',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bus',
            name='plate_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='status',
            field=models.CharField(choices=[('moving', 'En mouvement'), ('stopped', "À l'arrêt"), ('maintenance', 'En maintenance'), ('inactive', 'Inactif')], default='inactive', max_length=15),
        ),
        migrations.AlterField(
            model_name='bus',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
