# Generated by Django 4.2.29 on 2026-04-16 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_bus_driver_alter_bus_brand_alter_bus_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='driver',
        ),
    ]
